[package]
name = "reqwest-actix-stream"
version = "1.0.0"
authors = ["clia <clia@163.com>"]
edition = "2018"

[lib]
name = "reqwest_actix_stream"
path = "src/lib.rs"

[dependencies]
actix-web = "2.0"
futures = "0.3"
actix-http = "1.0"
reqwest = "0"
